### ISSUE TITLE
📊 Implementar Stack de Observabilidade (Grafana + Prometheus + Loki)

### ISSUE THREAD

**Issue by Danzokka** [Danzokka/CMS-Portfolio#17]
## 🎯 Objetivo
Implementar uma stack completa de observabilidade usando Docker com Grafana, Prometheus e Loki para monitoramento, métricas e logs da aplicação.

### Docker Compose Setup
- [ ] **Configuração base da stack**
  - Docker Compose para serviços de observabilidade
  - Networks isolados para segurança
  - Volumes persistentes para dados
  - Health checks para todos os serviços
  - Environment variables organizadas

- [ ] **Prometheus Configuration**
  - Configuração de scraping das aplicações
  - Service discovery automático
  - Rules e alerting básico
  - Retention policy adequada
  - Targets de monitoring

- [ ] **Grafana Setup**
  - Dashboards as code (provisioning)
  - Data sources auto-configurados
  - Pastas organizadas por domínio
  - Alerting channels configurados
  - Themes e branding

- [ ] **Loki Configuration**
  - Pipeline de log processing
  - Labels e parsing rules
  - Retention e storage config
  - Integration com aplicações
  - Log aggregation rules

### Application Instrumentation
- [ ] **NestJS Metrics (Backend)**
  - Prometheus metrics middleware
  - HTTP request metrics
  - Database query metrics
  - Custom business metrics
  - Error tracking e alerting

- [ ] **Next.js Monitoring (Frontend)**
  - Web vitals monitoring
  - Performance metrics
  - Error boundary reporting
  - User analytics básicas
  - Real User Monitoring (RUM)

- [ ] **Database Monitoring**
  - PostgreSQL exporter
  - Query performance metrics
  - Connection pool monitoring
  - Slow query tracking
  - Database health metrics

### Dashboards e Alerting
- [ ] **Application Dashboard**
  - Request rate, errors, duration
  - Database performance
  - Response time percentiles
  - Error rate trends
  - Active users online

- [ ] **Infrastructure Dashboard**
  - CPU, Memory, Disk usage
  - Network traffic
  - Container health status
  - Docker metrics
  - System load average

- [ ] **Business Metrics Dashboard**
  - New registrations
  - Project views
  - Blog post engagement
  - Review submissions
  - API usage patterns

- [ ] **Alerting Rules**
  - High error rate alerts
  - Response time degradation
  - Database connection issues
  - Memory/CPU threshold alerts
  - Disk space warnings

### Docker Compose Structure
```yaml
# docker-compose.observability.yml
services:
  # Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
```

### Estrutura de Arquivos
```
monitoring/
├── docker-compose.observability.yml
├── prometheus/
│   ├── prometheus.yml
│   └── rules/
│       ├── application.yml
│       └── infrastructure.yml
├── grafana/
│   ├── provisioning/
│   │   ├── datasources/
│   │   │   └── datasources.yml
│   │   └── dashboards/
│   │       └── dashboards.yml
│   └── dashboards/
│       ├── application-overview.json
│       ├── infrastructure-metrics.json
│       └── business-metrics.json
├── loki/
│   └── loki-config.yml
└── promtail/
    └── promtail-config.yml
```

### Application Metrics Implementation
- [ ] **NestJS Metrics**
  ```typescript
  // apps/api/src/common/metrics/metrics.service.ts
  @Injectable()
  export class MetricsService {
    private readonly httpRequestDuration: Histogram<string>
    private readonly httpRequestTotal: Counter<string>
    private readonly databaseQueryDuration: Histogram<string>
    
    // Implementar métricas customizadas
  }
  ```

- [ ] **Frontend Monitoring**
  ```typescript
  // apps/web/src/lib/monitoring.ts
  export const reportWebVitals = (metric: any) => {
    // Send to analytics endpoint
  }
  
  export const reportError = (error: Error) => {
    // Send to error tracking
  }
  ```

### Configuration Files
- [ ] **Prometheus Config**
  ```yaml
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  rule_files:
    - "rules/*.yml"

  scrape_configs:
    - job_name: 'cms-api'
      static_configs:
        - targets: ['host.docker.internal:5000']
      metrics_path: '/metrics'
      scrape_interval: 10s

    - job_name: 'cms-web'
      static_configs:
        - targets: ['host.docker.internal:3000']
      metrics_path: '/api/metrics'
      scrape_interval: 30s

    - job_name: 'postgres'
      static_configs:
        - targets: ['postgres-exporter:9187']
  ```

- [ ] **Grafana Provisioning**
  - Data sources automáticos
  - Dashboard import automático
  - Alerting channel setup
  - User management

### Dashboards Específicos
- [ ] **Application Performance**
  - Request throughput
  - Response time distribution
  - Error rate by endpoint
  - Database query performance
  - Cache hit rates

- [ ] **User Experience**
  - Core Web Vitals
  - Page load times
  - JavaScript errors
  - User session duration
  - Bounce rate tracking

- [ ] **Business Intelligence**
  - Daily/weekly active users
  - Content engagement metrics
  - Conversion funnels
  - Feature usage analytics
  - Growth metrics

### Alerting Setup
- [ ] **Critical Alerts**
  - Application down (> 5 min)
  - Error rate > 5%
  - Response time > 2s
  - Database connection failures
  - Memory usage > 80%

- [ ] **Warning Alerts**
  - Error rate > 1%
  - Response time > 1s
  - Disk usage > 70%
  - CPU usage > 70%
  - Unusual traffic patterns

## ✅ Critérios de Aceitação
- [ ] Stack de observabilidade está funcionando
- [ ] Dashboards carregam dados corretamente
- [ ] Métricas da aplicação são coletadas
- [ ] Logs são agregados no Loki
- [ ] Alerting está configurado e testado
- [ ] Performance impact é mínimo
- [ ] Dados persistem entre restarts
- [ ] Health checks funcionam
- [ ] Documentação está completa
- [ ] Backup e restore configurados

## 🏷️ Labels
`infrastructure` `monitoring` `docker` `observability` `devops`
